### ISSUE TITLE
Include "Extension" in Timetables API Response Object

### ISSUE THREAD

**Issue by spencer-b-318** [ciaranmccormick/python-bods-client#31]
The extension of a dataset (zip or xml) would be useful to include from the API response along with NOC, Status, Description etc. 

As it is much easier to parse the underlying data if it's known whether or not the dataset needs to be unzipped first.

**Comment by ciaranmccormick** [comment]
Thanks for opening the issue @spencer-b-318. I've published 0.10.0 which has everything you requested plus all the remaining fields that are available in the API but which I hadn't added to the package.

**Comment by spencer-b-318** [comment]
Great, thanks Ciaran
